name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:all

      - name: Generate Allure Report
        if: always()
        run: npm run test:allure

      - name: Deploy Allure Report to "report" branch
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan report
          git rm -rf .
          mv allure-report/* .
          rm -r allure-report
          touch .nojekyll  # Вимкнення обробки Jekyll для GH Pages
          git add .
          git commit -m "Update Allure report"
          git push --force origin report
